Models/ErrorViewModel.cs
using System;

namespace TodoListMvc.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/Todo.cs
using System;
using MongoDB.Bson;
using MongoDB.Bson.Serialization.Attributes;

namespace TodoListMvc.Models
{
    public class Todo
    {
        [BsonId]
        [BsonRepresentation(BsonType.ObjectId)]
        public string Id { get; set; }
        public string TodoWork { get; set; }
        public DateTime TodoDateTime { get; set; }
        public bool IsCompleted { get; set; }
    }
}

Models/TodoListViewModel.cs
using System.Collections.Generic;

namespace TodoListMvc.Models
{
    public class TodoListViewModel
    {
        public List<Todo> Todos { get; set; }
        public string CurrentTodo { get; set; }
    }
}

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using TodoListMvc.Application;
using TodoListMvc.Models;

namespace TodoListMvc.Controllers
{
    public class HomeController : Controller
    {
        private readonly TodoService _todoService;

        public HomeController(TodoService todoService)
        {
            _todoService = todoService;
        }

        public IActionResult NewTodo()
        {
            return View();
        }
        
        [HttpPost]
        public async Task<IActionResult> NewTodo(Todo newTodo)
        {
             newTodo.TodoDateTime = DateTime.Now;
             if(ModelState.IsValid)
             {
               await _todoService.CreateAsync(newTodo);
               return RedirectToAction("newTodo");
             }
            return View();
            
        }

    
        public async Task<IActionResult> DeleteTodo(string id)
        {
            
             if(ModelState.IsValid)
             {
               await _todoService.DeleteAsync(id);
               return RedirectToAction("NewTodo");
             }
            return View();
            
        }
        [HttpPost]
        public async Task<IActionResult> EditTodo(string id)
        {
            // newTodo.TodoDateTime = DateTime.Now;
       
             
             if(ModelState.IsValid)
             {
               
               var todo =  await _todoService.GetTodoAsync(id);
               todo.IsCompleted = todo.IsCompleted ? false : true;
               await _todoService.UpdateAsync(id, todo);
               
               return RedirectToAction("NewTodo", "Home");
             }
            return View();
            
        }
    }
}

ViewComponents/TodoListViewComponent.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ViewComponents;
using TodoListMvc.Application;
using TodoListMvc.Models;

namespace TodoListMvc.ViewComponents
{
    public class TodoListViewComponent:ViewComponent
    {
        private readonly TodoService _todoService;
        public TodoListViewComponent(TodoService todoService)
        {
            _todoService = todoService;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            var todos = await _todoService.GetTaskAsync();
            var model = new TodoListViewModel()
            {
              Todos =  todos,
              CurrentTodo = HttpContext.Request.Query["todo"]
            };

            return View(model);
        }
    }
}

Views/Home/NewTodo.cshtml
@model TodoListMvc.Models.Todo
@{
    ViewData["Title"] = "Home Page";
}


		<h1>todos</h1>
		<form asp-controller="Home" asp-action="NewTodo" method="post">
			<input asp-for="TodoWork" class="new-todo" placeholder="What needs to be done?" autoFocus />
		</form>


Views/Shared/Components/TodoList/Default.cshtml
@model TodoListMvc.Models.TodoListViewModel

<!-- This section should be hidden by default and shown when there are todos -->
	<section hidden="@(Model.Todos.Count < 1)" id="main" class="main">

		<input property="toggleAll" EditTodos(this) id="toggle-all"
				 class="toggle-all" type="checkbox"
				 checked="[todoLeft = 0]">
		<label for="toggle-all" mv-action="set(done, !toggleAll)">
			Mark all as complete
		</label>
		<ul class="todo-list">
			
		 @foreach (var todo in Model.Todos)
         {
			var selectedcss = todo.IsCompleted ? "completed" : "none";
			

         <li  class="@selectedcss">
				<div class="view">
					
					<input id="@todo.Id"   onchange="EditTodo(this)" value="@todo.IsCompleted" checked='@todo.IsCompleted' class="toggle" type="checkbox" />
			
					<label>@todo.TodoWork</label>
					<a asp-action="DeleteTodo" asp-route-id="@todo.Id" asp-controller="Home" class="btn destroy"></a>
				</div>
			</li>
         }
		</ul>
	</section>
	<!-- This footer should hidden by default and shown when there are todos -->

   

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TodoListMvc</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/css/style.css" />
</head>
<body>
<section mv-app="todoapp" class="todoapp"
			mv-bar="none" mv-storage="local"
			mv-autosave="3"
			mv-mode="edit"
			mv-init="#data">
	<header class="header">
		@RenderBody()
	</header>
	 @await Component.InvokeAsync("TodoList")
	<footer hidden="[count(todo) = 0]" class="footer">
		
		<meta property="todoDone" content="[count(todo where done)]">
		<meta property="todoLeft" content="[count(todo where !done)]">
		
		<!-- This should be `0 items left` by default -->
		<span class="todo-count">
			<strong mv-value="todoLeft">0</strong>
			[if(todoLeft = 1, 'item', 'items')] left
		</span>

		<meta property="activeFilter" content="all" mv-storage="none">
		<ul class="filters">
			<li>
				<a class="[if(activeFilter = 'all', 'selected')]"
					mv-action="set(activeFilter, 'all')">All</a>
			</li>
			<li>
				<a class="[if(activeFilter = 'active', 'selected')]"
					mv-action="set(activeFilter, 'active')">Active</a>
			</li>
			<li>
				<a class="[if(activeFilter = 'completed', 'selected')]"
					mv-action="set(activeFilter, 'completed')">Completed</a>
			</li>
		</ul>
		<!-- Hidden if no completed items are left ↓ -->
		<button hidden="[todoDone = 0]"
				  class="clear-completed"
				  mv-action="delete(todo where done)">
			Clear completed
		</button>
	</footer>
</section>
<footer class="info">
	<p>Click to edit a todo</p>
	<p>Created by <a href="https://d12n.me/">Dmitry Sharabin</a></p>
	<p>Part of <a href="http://todomvc.com">TodoMVC</a></p>
</footer>




     </div>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>